name: notes
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  rename_app: ^1.6.1
  change_app_package_name: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/svg/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/splash.svg
    - assets/svg/logo.png

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
